### PR TITLE
Fix TypeScript definitions

### PR DESCRIPTION
**Pull request by vslinko**

### CODE REVIEW

**Comment by blakeembrey** [comment]
Can you please elaborate on what you changed? This signature already existed.

**Comment by vslinko** [comment]
@blakeembrey TypeScript isn't using definition of function declaration when other definitions found:

https://www.typescriptlang.org/play/index.html#src=function%20a(x%3A%20number)%3A%20void%3B%0D%0A%0D%0Afunction%20a(x%3A%20number%2C%20y%3F%3A%20string)%3A%20void%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Aa(1%2C%20'')%3B%0D%0A

https://www.typescriptlang.org/play/index.html#src=function%20a(x%3A%20number)%3A%20void%3B%0D%0Afunction%20a(x%3A%20number%2C%20y%3F%3A%20string)%3A%20void%3B%0D%0A%0D%0Afunction%20a(x%3A%20number%2C%20y%3F%3A%20string)%3A%20void%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Aa(1%2C%20'')%3B%0D%0A

**Comment by blakeembrey** [comment]
Thanks. I must have forgotten about the overloading requirement. Would be nice if TypeScript errored here, since it does when they are truly incompatible. 

Can you follow the existing style when committing?

**Comment by vslinko** [comment]
@blakeembrey done

**Pull request merged**
